<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReglaProveedorSeeder extends Seeder
{
    public function run(): void
    {
        $reglas = [
            ['14297884-9','CESAR GABRIEL AGUILERA ARANDA','Gastos Generales'],
            ['78924030-2','IMPLEMENTOS S.A.','Gastos Generales'],
            ['76418719-9','Ferreteria Arnoldo Arteaga e Hijos Ltda.','Gastos Generales'],
            ['96704460-1','FERBRAS S.A.','Costos Directo por Venta PVC'],
            ['79706120-4','ESMAX RED LIMITADA','Bencina'],
            ['77038466-4','COMERCIALIZADORA ESKIMO SPA','Otros Egresos Fuera de Explotación'],
            ['76904007-2','COMERCIAL OLEOFLEX LOS ANGELES LIMITADA','Otros Gastos de Administración y Venta'],
            ['76378611-0','COMBUSTIBLES COIHUECO LIMITADA','Bencina'],
            ['77883350-6','COMERCIAL BORGEAUD LIMITADA','Repuestos/Arreglos'],
            ['79906540-1','Cargo Trader SPA','Transporte/Encomiendas'],
            ['91139000-0','Automotora Comercial Costabal y Echeniqu','Repuestos/Arreglos'],
            ['76292207-k','SOCIEDAD INDUSTRIAL Y COMERCIAL ENERGLASS LTDA','Otros Costos Directos del Giro'],
            ['96689310-9','TRANSBANK S.A.','Comisiones Pagadas'],
            ['90635000-9','Telefónica Chile S.A','Gastos Generales'],
            ['96792430-k','SODIMAC S.A.','Gastos Generales'],
            ['76417897-1','SOCIEDAD COMERCIAL SANTA MAGDALENA SPA','Bencina'],
            ['78004800-k','SOC DE INVERSIONES STEVENS LIMITADA','Bencina'],
            ['81537600-5','RENDIC HERMANOS S.A.','Otros Gastos de Administración y Venta'],
            ['77398220-1','MercadoLibre Chile LTDA','Otros Gastos de Administración y Venta'],
            ['5135505-9','MARIA ELENA SAAVEDRA CONCHA','Costos Directo por Venta Aluminio y Termopanel'],
            ['78627210-6','HIPERMERCADOS TOTTUS S.A.','Otros Gastos de Administración y Venta'],
            ['77542278-5','ENERGIA Y SERVICIOS SPA','Bencina'],
            ['96806980-2','Entel PCS Telecomunicaciones S.A.','Gastos Generales'],
            ['76568660-1','EASY RETAIL S.A.','Otros Costos Directos del Giro'],
            ['77049423-0','DISTRIBUIDORA E IMPORTADORA DITOR  SPA','Gastos Generales'],
            ['77134011-3','CONSTANZA ZIPPEL Y CIA  LTDA','Bencina'],
            ['76598819-5','COMERCIALIZADORA DE MATERIALES DE FERRETERIA LTDA','Otros Costos Directos del Giro'],
            ['79831880-2','Comercial Scanavini Limitada','Costos Directo por Venta Aluminio y Termopanel'],
            ['77459964-9','Comercial Icaros Ltda.','Repuestos/Arreglos'],
            ['99527620-8','COMERCIAL DIVENSER S.A.','Repuestos/Arreglos'],
            ['99225000-3','CHUBB SEGUROS CHILE S.A.','Seguros'],
            ['96756430-3','CHILEXPRESS S.A.','Transporte/Encomiendas'],
            ['97004000-5','Banco de Chile','Gastos Financieros'],
            ['96671320-8','ASSA ABLOY CHILE SPA','Costos Directo por Venta PVC'],
            ['76050454-8','ARRIENDO DE MAQUINARIAS OLALDE Y OLALDE LIMITADA','Gastos Generales'],
            ['76134941-4','ADMIN. DE SUPERMERCADOS HIPER LIMITADA','Gastos Generales'],
            ['96355000-6','ELECTROCOM S.A.','Costos Directo por Venta Aluminio y Termopanel'],
            ['76545380-1','METALMECANICA ABURTO Y ABURTO LIMITADA','Costos Directo por Venta Aluminio y Termopanel'],
            ['76294294-1','ROULIEZ Y CALDERÓN SOFTWARE WINPERFIL CHILE LIMITADA','Gastos de Investigación y Desarrollo'],
            ['76411321-7','CGE S.A','Luz'],
            ['76172387-1','SOCIEDAD CONCESIONARIA VALLES DEL BIO BIO SA','Transporte/Encomiendas'],
            ['76376061-8','SOCIEDAD CONCESIONARIA VESPUCIO ORIENTE S.A.','Transporte/Encomiendas'],
            ['76882345-6','Sociedad Concesionaria Ruta Nahuelbuta S.A.','Transporte/Encomiendas'],
            ['77722758-0','SOCIEDAD CONCESIONARIA RUTA 5 CHILLAN-COLLIPULLI S.A.','Transporte/Encomiendas'],
            ['96571160-0','REHAU S A','Costos Directo por Venta PVC'],
            ['76967670-8','COTIZACION CLIENTE - CONCEPCION','Costos Directo por Venta PVC'],
            ['76084620-1','SERMAHIN LTDA','Repuestos/Arreglos'],
            ['77916138-2','COMERCIAL Y SERVICIOS IDELLA MAPASE LIMITADA','Bencina'],
            ['76506171-7','CRO DISTRIBUIDORA COMBUSTIBLES LTDA.','Bencina'],
            ['96537940-1','SOCIEDAD DISTRIBUIDORA DE ALUMINIO S.A.','Costos Directo por Venta Aluminio y Termopanel'],
            ['88473200-k','ADMINISTRACION Y GESTION DE ESTACIONES D','Bencina'],
            ['77001730-0','IMPORTADORA Y EXPORTADORA WUALUM LTDA.','Costos Directo por Venta Aluminio y Termopanel'],
            ['12320138-8','VIELMET','Costos Directo por Venta Aluminio y Termopanel'],
            ['14479711-6','CAROLINA MABEL NAMUNCURA ARAYA','Almuerzos'],
            ['96656410-5','BICE VIDA COMPAÑIA DE SEGUROS S.A.','Seguros'],
            ['76430191-9','SANTA MARIA SPA','Almuerzos'],
            ['76733630-6','RIFFO DELGADO LTDA.','Costos Directo por Venta Aluminio y Termopanel'],
            ['78441520-1','SOC AGRICOLA COMERCIAL BENCINERA TURIST','Bencina'],
            ['97080000-k','BANCO BICE','Gastos Financieros'],
            ['76569708-5','COMERCIALIZADORA RASSEC LIMITADA','Costos Directo por Venta PVC'],
            ['76762740-8','SOC. COMERC. DE REPUESTOS S.A.','Repuestos/Arreglos'],
            ['77937068-2','FERRETERIA CONSTRUCASSA LIMITADA','Costos Directo por Venta Aluminio y Termopanel'],
            ['76806773-2','IMPORTADORA Y COMERCIALIZADORA EL SUPREMO LIMITADA','Costos Directo por Venta Aluminio y Termopanel'],
            ['83366800-5','ANTONIO CASTILLO S.A.','Repuestos/Arreglos'],
            ['83935900-4','VIDRIERIA PRAT S.A.','Costos Directo por Venta Aluminio y Termopanel'],
            ['76057350-7','ALUMINIOS 2000 LTDA','Costos Directo por Venta Aluminio y Termopanel'],
            ['76102404-3','HAUSTEK S.A','Costos Directo por Venta PVC'],
            ['76072694-k','Comercial Soluex SPA','Costos Directo por Venta Aluminio y Termopanel'],
            ['77675220-7','FERREX S.A.','Costos Directo por Venta Aluminio y Termopanel'],
            ['77082930-5','MALVOA COMERCIAL Y CIA.  LTDA.','Bencina'],
            ['81548400-2','MILAN FABJANOVIC SPA','Costos Directo por Venta Aluminio y Termopanel'],
            ['89622400-k','PULLMAN CARGO S.A','Transporte/Encomiendas'],
            ['80983500-6','TRANSPORTES CRUZ DEL SUR LTDA.','Transporte/Encomiendas'],
            ['77678220-3','ALUMINIOS Y VIDRIOS METALVID S.A.','Costos Directo por Venta Aluminio y Termopanel'],
            ['81585900-6','COOPERATIVA ELECTRICA LOS ANGELES LTDA.','Sueldos Administrativos'],
            ['77212910-6','FERRETERIA FERROPERNO LTDA','Costos Directo por Venta Aluminio y Termopanel'],
            ['76046809-6','DAP DUCASSE DISENO LTDA.','Costos Directo por Venta Aluminio y Termopanel'],
            ['78610460-2','DISTRIB. Y COMERC. DIALUM S.A.','Costos Directo por Venta Aluminio y Termopanel'],
            ['78484900-7','TECNICAL COMERCIALIZADORA DE  ALUMINIOS','Costos Directo por Venta Aluminio y Termopanel'],
            ['76424331-5','ALCHILE SPA','Costos Directo por Venta Aluminio y Termopanel'],
            ['76058647-1','VERISURE CHILE SPA','Seguros'],
            ['94510000-1','Renta Nacional Compañia de Seguros Generales S.A','Seguros'],
            ['77660960-9','Acenor Aceros Del Norte S.A.','Gastos Generales'],
            ['78885550-8','PERSONAL COMPUTER FACTORY S.A.','Gastos Generales'],
            ['76620001-k','VEXZETA TECNOLOGIA SPA','Gastos de Investigación y Desarrollo'],
            ['76866551-6','COMERCIALIZADORA DE MATERIALES Y CONSTRUCTORA O & M LIMITADA','Otros Costos Directos del Giro'],
            ['76550081-8','Chipax SpA','Gastos de Investigación y Desarrollo'],
            ['76136144-9','BSALE CHILE S A','Gastos de Investigación y Desarrollo'],
            ['88755700-4','COMERCIAL CENTER LTDA.','Gastos Generales'],
            ['76802739-0','COMBUSTIBLES SANTA INES DE CURICHE LTDA','Bencina'],
            ['76149375-2','COMBUSTIBLES LOS ANGELES LTDA','Bencina'],
            ['77363442-4','ALFECAR Y CIA LIMITADA','Bencina'],
            ['78701740-1','WURTH CHILE LIMITADA','Otros Costos Directos del Giro'],
            ['76444456-6','COMERCIAL Y SERVICIOS ALUN LIMITADA','Bencina'],
            ['77195820-6','COMERCIAL MONSERRAT LIMITADA','Bencina'],
            ['94625000-7','INVERSIONES ENEX S.A.','Bencina'],
            ['99061000-2','LIBERTY COMPAÑIA DE SEGUROS GENERALES S.A.','Seguros'],
            ['76173152-1','INVERSIONES ESCORPION LIMITADA','Bencina'],
            ['77174633-0','INVERSIONES HEREDIA Y CIA LIMITADA','Bencina'],
            ['96945440-8','SOC CONCESIONARIA AUTOPISTA CENTRAL S A','Transporte/Encomiendas'],
            ['96875230-8','RUTA DEL MAIPO SOCIEDAD CONCESIONARIA S.A.','Transporte/Encomiendas'],
            ['76496130-7','Sociedad Concesionaria Costanera Norte S.A.','Transporte/Encomiendas'],
            ['96820630-3','SOCIEDAD CONCESIONARIA AUTOPISTA DEL ACONCAGUA S.A.','Transporte/Encomiendas'],
            ['77386869-7','R&C FERRETERIA INDUSTRIAL SPA','Costos Directo por Venta Aluminio y Termopanel'],
            ['76013445-7','ALSO COMERCIAL Y SERVICIOS LIMITADA','Costos Directo por Venta Aluminio y Termopanel'],
            ['77073132-1','Ferreteria MultiService SpA','Costos Directo por Venta Aluminio y Termopanel'],
            ['77337752-9','SOCIEDAD CONCESIONARIA RUTA 5 TALCA-CHILLAN S.A.','Transporte/Encomiendas'],
            ['96992030-1','Sociedad Concesionaria Vespucio Norte Express S.A.','Transporte/Encomiendas'],
            ['76052927-3','Soc. Conc. Autopista Nueva Vespucio Sur S.A.','Transporte/Encomiendas'],
            ['76696318-8','FERRETERIA COCHRANE SPA','Costos Directo por Venta Aluminio y Termopanel'],
            ['76472852-1','ALUMINIOS Y METALES LTDA.','Costos Directo por Venta Aluminio y Termopanel'],
            ['97036000-k','Santander - Chile','Gastos Financieros'],
            ['76211240-k','TRANSPORTES TECNOLOGIA Y GIROS EGT LTDA.','Transporte/Encomiendas'],
            ['99147000-k','BCI SEGUROS GENERALES S.A.','Seguros'],
            ['76502941-4','MANQUEHUE PVC SPA','Costos Directo por Venta PVC'],
            ['99520000-7','COPEC S.A.','Bencina'],
            ['94623000-6','SODEXO CHILE SPA','Gastos Generales'],
            ['76329526-5','COMERCIAL FULL-SELLO LTDA.','Costos Directo por Venta Aluminio y Termopanel'],
            ['76033213-5','EMPRESA DE TRANSPORTES VARMONTT LIMITADA','Transporte/Encomiendas'],
            ['77215640-5','ADMINISTRADORA DE VENTAS AL DETALLE LTDA','Bencina'],
        ];

        $now = now();
        foreach ($reglas as [$rut, $nombre, $categoria]) {
            DB::table('reglas_categoria_proveedor')->updateOrInsert(
                ['rut_emisor' => mb_strtolower($rut)],
                ['nombre_emisor' => $nombre, 'categoria' => $categoria, 'updated_at' => $now, 'created_at' => $now]
            );
        }

        // Aplicar reglas a compras existentes
        DB::update("
            UPDATE compras c
            JOIN reglas_categoria_proveedor r ON LOWER(c.rut_emisor) = LOWER(r.rut_emisor)
            SET c.categoria = r.categoria
        ");
    }
}
