/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'agregar-producto': RouteRecordInfo<'agregar-producto', '/agregar-producto', Record<never, never>, Record<never, never>>,
    'agregar-ventana-modal': RouteRecordInfo<'agregar-ventana-modal', '/AgregarVentanaModal', Record<never, never>, Record<never, never>>,
    'agregar-ventana-modal2': RouteRecordInfo<'agregar-ventana-modal2', '/AgregarVentanaModal2', Record<never, never>, Record<never, never>>,
    'clientes': RouteRecordInfo<'clientes', '/clientes', Record<never, never>, Record<never, never>>,
    'cliente-table': RouteRecordInfo<'cliente-table', '/ClienteTable', Record<never, never>, Record<never, never>>,
    'comprasmensuales': RouteRecordInfo<'comprasmensuales', '/comprasmensuales', Record<never, never>, Record<never, never>>,
    'cotizacion-editar': RouteRecordInfo<'cotizacion-editar', '/cotizacion-editar', Record<never, never>, Record<never, never>>,
    'cotizacion-ver': RouteRecordInfo<'cotizacion-ver', '/cotizacion-ver', Record<never, never>, Record<never, never>>,
    'cotizaciones': RouteRecordInfo<'cotizaciones', '/cotizaciones', Record<never, never>, Record<never, never>>,
    'cotizador': RouteRecordInfo<'cotizador', '/cotizador', Record<never, never>, Record<never, never>>,
    'cotizador-index copy': RouteRecordInfo<'cotizador-index copy', '/cotizador/index copy', Record<never, never>, Record<never, never>>,
    'cotizador-index-posiblenuevo': RouteRecordInfo<'cotizador-index-posiblenuevo', '/cotizador/indexPOSIBLENUEVO', Record<never, never>, Record<never, never>>,
    'cotizador2': RouteRecordInfo<'cotizador2', '/cotizador2', Record<never, never>, Record<never, never>>,
    'dashboardventas': RouteRecordInfo<'dashboardventas', '/dashboardventas', Record<never, never>, Record<never, never>>,
    'facturacion': RouteRecordInfo<'facturacion', '/facturacion', Record<never, never>, Record<never, never>>,
    'lista-precios': RouteRecordInfo<'lista-precios', '/lista-precios', Record<never, never>, Record<never, never>>,
    'lista-precios-modal-precio': RouteRecordInfo<'lista-precios-modal-precio', '/lista-precios/ModalPrecio', Record<never, never>, Record<never, never>>,
    'listado-productos': RouteRecordInfo<'listado-productos', '/listado-productos', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'modal-productos': RouteRecordInfo<'modal-productos', '/ModalProductos', Record<never, never>, Record<never, never>>,
    'productos': RouteRecordInfo<'productos', '/productos', Record<never, never>, Record<never, never>>,
    'productos-producto-form': RouteRecordInfo<'productos-producto-form', '/productos/ProductoForm', Record<never, never>, Record<never, never>>,
    'productos-productos-list': RouteRecordInfo<'productos-productos-list', '/productos/ProductosList', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'ventana-form': RouteRecordInfo<'ventana-form', '/VentanaForm', Record<never, never>, Record<never, never>>,
    'ventanapreview': RouteRecordInfo<'ventanapreview', '/ventanapreview', Record<never, never>, Record<never, never>>,
    'visor': RouteRecordInfo<'visor', '/visor', Record<never, never>, Record<never, never>>,
    'visor3d': RouteRecordInfo<'visor3d', '/visor3d', Record<never, never>, Record<never, never>>,
  }
}
